TRANSLATIONS = {
    "en": {
        # Common Actions
        "edit": "Edit",
        "delete": "Delete",
        "cancel": "Cancel",
        "back": "Back",
        "submit": "Submit",
        "save_changes": "Save Changes",
        "close": "Close",
        "points_label": "points",
        
        # Sidebar / Navigation
        "dashboard": "Dashboard",
        "my_progress": "My Progress",
        "profile": "Profile",
        "eco_feed": "Eco Feed",
        "friends": "Friends",
        "groups": "Groups",
        "leaderboard": "Leaderboard",
        "missions": "Missions",
        "frame_shop": "Frame Shop",
        "share_action": "Share Action",
        "logout": "Logout",
        "login": "Login",
        "register": "Register",
        "eco_tracker": "Eco Tracker",
        "settings": "Settings",
        "language": "Language",
        "select_language": "Select Language",
        "save": "Save Changes",
        "change_password": "Change Password",
        
        # Profile details
        "eco_profile": "Eco Profile",
        "streak": "day streak",
        "joined_since": "Joined Since",
        "current_level": "Current Level",
        "total_eco_score": "Total Eco Score",
        "actions_completed": "Actions Completed",
        "level_progress": "Level Progress",
        "achievements": "Achievements",
        "earned_badges": "Earned Badges",
        "habits": "Habits",
        "green_habits": "Green Habits",
        "actions": "Actions",
        "most_common_category": "Most Common Category",
        "eco_identity": "Eco Identity",
        "next_goal": "Next Goal",
        "recent_activity": "Recent Activity",
        "your_latest_eco_actions": "Your Latest Eco Actions",
        
        # Dashboard details
        "welcome_back": "Welcome back",
        "eco_stats_at_a_glance": "Your environmental impact stats at a glance",
        "daily_missions": "Daily Missions",
        "complete_tasks_to_earn_points": "Complete tasks to earn points",
        "completed": "Completed",
        "pending": "Pending",
        "weekly_quest": "Weekly Quest",
        "coop_quest": "Co-op Quest",
        "members": "members",
        "join_group_to_participate": "Join or create a group to participate in weekly challenges!",
        "trivia_of_the_day": "Trivia of the Day",
        "answer_trivia_to_earn_points": "Answer daily trivia questions to earn points",
        "ai_coach_tip": "AI Eco Coach Advice",
        "motivated_eco_tip": "Your personal AI recommendation for today",
        "upload_image": "Upload Image",
        "caption": "Caption",
        
        # Progress Page
        "my_progress_title": "My Progress & Activity",
        "progress_sub": "Track your achievements, check levels, and review stats.",
        "eco_stats": "Eco Stats",
        "levels_roadmap": "Levels Roadmap",
        "days_streak": "Days Streak",
        "unlocked": "Unlocked",
        "locked": "Locked",
        "pts": "pts",
        "progress_bar": "Progress Bar",
        "remaining_points": "points remaining to next level",
        
        # Social Feed Page
        "eco_feed_title": "Eco Social Feed",
        "feed_sub": "Stay motivated by checking out green activities from around the globe.",
        "global_feed": "Global Feed",
        "friends_feed": "Friends Feed",
        "like": "Like",
        "comment": "Comment",
        "react": "Eco React",
        "write_comment": "Write a comment...",
        "no_actions": "No eco actions posted yet.",
        "post": "Post",
        
        # Friends Page
        "friends_title": "Friend Center",
        "friends_sub": "Find friends, compare stats, and accept incoming invitations.",
        "search_users": "Search Users",
        "send_request": "Add Friend",
        "friend_requests": "Incoming Requests",
        "pending_requests": "Pending Requests",
        "my_friends_list": "My Friends List",
        "accept": "Accept",
        "reject": "Reject",
        "remove": "Remove Friend",
        "no_friends_found": "No friends found.",
        "compare_stats": "Compare Statistics",
        "your_points": "Your Points",
        "friend_points": "Friend Points",
        "their_level": "Their Level",
        
        # Groups Page & Details
        "groups_title": "Eco Groups",
        "groups_sub": "Team up with friends to complete Weekly Challenges and double your rewards.",
        "create_group": "Create Group",
        "group_name": "Group Name",
        "active_quest": "Weekly Group Quest",
        "group_members": "Group Members",
        "group_invites": "Group Invites",
        "leave_group": "Leave Group",
        "delete_group": "Delete Group",
        "no_groups": "You are not a member of any group yet.",
        "invite_members": "Invite Member",
        "search_username": "Enter username to invite...",
        "invite_sent": "Invite Sent",
        "max_members_limit": "Max 5 members allowed.",
        "weekly_quest_desc": "Group Weekly Quest",
        
        # Leaderboard Page
        "leaderboard_title": "Eco Leaderboard",
        "leaderboard_sub": "Check your standing in the global green community, friends, or groups.",
        "global_rank": "Global Leaderboard",
        "friends_rank": "Friends Leaderboard",
        "group_rank": "Group Leaderboard",
        "rank": "Rank",
        "user": "User",
        "score": "Total Score",
        
        # Frame Shop Page
        "frame_shop_title": "Avatar Frame Shop",
        "frame_shop_sub": "Spend your points on premium animated avatar borders.",
        "buy": "Purchase Frame",
        "equip": "Equip",
        "unequip": "Unequip",
        "owned_frame": "Owned",
        "insufficient_points": "Insufficient Points",
        
        # Missions Center Page
        "missions_title": "Eco Missions Center",
        "missions_sub": "Perform environmental tasks to gain points and level up.",
        "daily_missions_list": "Daily Missions",
        "weekly_missions_list": "Weekly Objectives",
        
        # Upload/Edit Action Page
        "upload_action_title": "Share Eco Action",
        "upload_sub": "Choose a category, write a caption, and let Gemini AI verify your deed.",
        "edit_action_title": "Edit Action Details",
        "select_image": "Select Action Photo",
        "enter_caption": "What did you do to help the environment?",
        "submit_for_ai": "Submit for AI Verification",
        "choose_file": "Choose File",
        "update_action": "Update Action",
    }
}


def language_translations(request):
    return {
        "t": TRANSLATIONS["en"],
        "current_lang": "en",
    }
