TRANSLATIONS = {
    "en": {
        # Common Actions
        "edit": "Edit",
        "delete": "Delete",
        "cancel": "Cancel",
        "back": "Back",
        "submit": "Submit",
        "save_changes": "Save Changes",
        "close": "Close",
        "points_label": "points",
        
        # Sidebar / Navigation
        "dashboard": "Dashboard",
        "my_progress": "My Progress",
        "profile": "Profile",
        "eco_feed": "Eco Feed",
        "friends": "Friends",
        "groups": "Groups",
        "leaderboard": "Leaderboard",
        "missions": "Missions",
        "frame_shop": "Frame Shop",
        "share_action": "Share Action",
        "logout": "Logout",
        "login": "Login",
        "register": "Register",
        "eco_tracker": "Eco Tracker",
        "settings": "Settings",
        "language": "Language",
        "select_language": "Select Language",
        "save": "Save Changes",
        "change_password": "Change Password",
        
        # Profile details
        "eco_profile": "Eco Profile",
        "streak": "day streak",
        "joined_since": "Joined Since",
        "current_level": "Current Level",
        "total_eco_score": "Total Eco Score",
        "actions_completed": "Actions Completed",
        "level_progress": "Level Progress",
        "achievements": "Achievements",
        "earned_badges": "Earned Badges",
        "habits": "Habits",
        "green_habits": "Green Habits",
        "actions": "Actions",
        "most_common_category": "Most Common Category",
        "eco_identity": "Eco Identity",
        "next_goal": "Next Goal",
        "recent_activity": "Recent Activity",
        "your_latest_eco_actions": "Your Latest Eco Actions",
        
        # Dashboard details
        "welcome_back": "Welcome back",
        "eco_stats_at_a_glance": "Your environmental impact stats at a glance",
        "daily_missions": "Daily Missions",
        "complete_tasks_to_earn_points": "Complete tasks to earn points",
        "completed": "Completed",
        "pending": "Pending",
        "weekly_quest": "Weekly Quest",
        "coop_quest": "Co-op Quest",
        "members": "members",
        "join_group_to_participate": "Join or create a group to participate in weekly challenges!",
        "trivia_of_the_day": "Trivia of the Day",
        "answer_trivia_to_earn_points": "Answer daily trivia questions to earn points",
        "ai_coach_tip": "AI Eco Coach Advice",
        "motivated_eco_tip": "Your personal AI recommendation for today",
        "upload_image": "Upload Image",
        "caption": "Caption",
        
        # Progress Page
        "my_progress_title": "My Progress & Activity",
        "progress_sub": "Track your achievements, check levels, and review stats.",
        "eco_stats": "Eco Stats",
        "levels_roadmap": "Levels Roadmap",
        "days_streak": "Days Streak",
        "unlocked": "Unlocked",
        "locked": "Locked",
        "pts": "pts",
        "progress_bar": "Progress Bar",
        "remaining_points": "points remaining to next level",
        
        # Social Feed Page
        "eco_feed_title": "Eco Social Feed",
        "feed_sub": "Stay motivated by checking out green activities from around the globe.",
        "global_feed": "Global Feed",
        "friends_feed": "Friends Feed",
        "like": "Like",
        "comment": "Comment",
        "react": "Eco React",
        "write_comment": "Write a comment...",
        "no_actions": "No eco actions posted yet.",
        "post": "Post",
        
        # Friends Page
        "friends_title": "Friend Center",
        "friends_sub": "Find friends, compare stats, and accept incoming invitations.",
        "search_users": "Search Users",
        "send_request": "Add Friend",
        "friend_requests": "Incoming Requests",
        "pending_requests": "Pending Requests",
        "my_friends_list": "My Friends List",
        "accept": "Accept",
        "reject": "Reject",
        "remove": "Remove Friend",
        "no_friends_found": "No friends found.",
        "compare_stats": "Compare Statistics",
        "your_points": "Your Points",
        "friend_points": "Friend Points",
        "their_level": "Their Level",
        
        # Groups Page & Details
        "groups_title": "Eco Groups",
        "groups_sub": "Team up with friends to complete Weekly Challenges and double your rewards.",
        "create_group": "Create Group",
        "group_name": "Group Name",
        "active_quest": "Weekly Group Quest",
        "group_members": "Group Members",
        "group_invites": "Group Invites",
        "leave_group": "Leave Group",
        "delete_group": "Delete Group",
        "no_groups": "You are not a member of any group yet.",
        "invite_members": "Invite Member",
        "search_username": "Enter username to invite...",
        "invite_sent": "Invite Sent",
        "max_members_limit": "Max 5 members allowed.",
        "weekly_quest_desc": "Group Weekly Quest",
        
        # Leaderboard Page
        "leaderboard_title": "Eco Leaderboard",
        "leaderboard_sub": "Check your standing in the global green community, friends, or groups.",
        "global_rank": "Global Leaderboard",
        "friends_rank": "Friends Leaderboard",
        "group_rank": "Group Leaderboard",
        "rank": "Rank",
        "user": "User",
        "score": "Total Score",
        
        # Frame Shop Page
        "frame_shop_title": "Avatar Frame Shop",
        "frame_shop_sub": "Spend your points on premium animated avatar borders.",
        "buy": "Purchase Frame",
        "equip": "Equip",
        "unequip": "Unequip",
        "owned_frame": "Owned",
        "insufficient_points": "Insufficient Points",
        
        # Missions Center Page
        "missions_title": "Eco Missions Center",
        "missions_sub": "Perform environmental tasks to gain points and level up.",
        "daily_missions_list": "Daily Missions",
        "weekly_missions_list": "Weekly Objectives",
        
        # Upload/Edit Action Page
        "upload_action_title": "Share Eco Action",
        "upload_sub": "Choose a category, write a caption, and let Gemini AI verify your deed.",
        "edit_action_title": "Edit Action Details",
        "select_image": "Select Action Photo",
        "enter_caption": "What did you do to help the environment?",
        "submit_for_ai": "Submit for AI Verification",
        "choose_file": "Choose File",
        "update_action": "Update Action",
    },
    "vi": {
        # Common Actions
        "edit": "Chỉnh sửa",
        "delete": "Xóa bỏ",
        "cancel": "Hủy bỏ",
        "back": "Quay lại",
        "submit": "Gửi đi",
        "save_changes": "Lưu thay đổi",
        "close": "Đóng",
        "points_label": "điểm",
        
        # Sidebar / Navigation
        "dashboard": "Bảng điều khiển",
        "my_progress": "Tiến trình",
        "profile": "Hồ sơ cá nhân",
        "eco_feed": "Bản tin Eco",
        "friends": "Bạn bè",
        "groups": "Nhóm của tôi",
        "leaderboard": "Bảng xếp hạng",
        "missions": "Nhiệm vụ",
        "frame_shop": "Cửa hàng khung",
        "share_action": "Chia sẻ hành động",
        "logout": "Đăng xuất",
        "login": "Đăng nhập",
        "register": "Đăng ký",
        "eco_tracker": "Eco Tracker",
        "settings": "Cài đặt",
        "language": "Ngôn ngữ",
        "select_language": "Chọn ngôn ngữ",
        "save": "Lưu thay đổi",
        "change_password": "Đổi mật khẩu",
        
        # Profile details
        "eco_profile": "Hồ sơ Eco",
        "streak": "ngày liên tiếp",
        "joined_since": "Tham gia từ",
        "current_level": "Cấp độ hiện tại",
        "total_eco_score": "Tổng điểm Eco",
        "actions_completed": "Hành động đã làm",
        "level_progress": "Tiến trình cấp độ",
        "achievements": "Thành tích",
        "earned_badges": "Danh hiệu đã đạt",
        "habits": "Thói quen",
        "green_habits": "Thói quen xanh",
        "actions": "Hành động",
        "most_common_category": "Danh mục phổ biến nhất",
        "eco_identity": "Danh hiệu Eco",
        "next_goal": "Mục tiêu tiếp theo",
        "recent_activity": "Hoạt động gần đây",
        "your_latest_eco_actions": "Hành động Eco mới nhất",
        
        # Dashboard details
        "welcome_back": "Chào mừng quay trở lại",
        "eco_stats_at_a_glance": "Thống kê tác động môi trường của bạn",
        "daily_missions": "Nhiệm vụ hàng ngày",
        "complete_tasks_to_earn_points": "Hoàn thành nhiệm vụ để tích lũy điểm thưởng",
        "completed": "Đã hoàn thành",
        "pending": "Chờ thực hiện",
        "weekly_quest": "Nhiệm vụ tuần",
        "coop_quest": "Hợp tác nhóm",
        "members": "thành viên",
        "join_group_to_participate": "Hãy tạo hoặc tham gia nhóm để cùng làm nhiệm vụ tuần nhé!",
        "trivia_of_the_day": "Trắc nghiệm hàng ngày",
        "answer_trivia_to_earn_points": "Trả lời câu đố môi trường để nhận điểm thưởng",
        "ai_coach_tip": "Góc AI Eco Coach tư vấn",
        "motivated_eco_tip": "Gợi ý sống xanh cá nhân hóa hôm nay",
        "upload_image": "Tải ảnh lên",
        "caption": "Chú thích ảnh",
        
        # Progress Page
        "my_progress_title": "Tiến trình & Hoạt động",
        "progress_sub": "Theo dõi thành tựu, xem lộ trình cấp độ và thống kê hoạt động.",
        "eco_stats": "Thống kê Eco",
        "levels_roadmap": "Lộ trình cấp độ",
        "days_streak": "Chuỗi ngày liên tục",
        "unlocked": "Đã mở",
        "locked": "Khóa",
        "pts": "điểm",
        "progress_bar": "Thanh tiến trình",
        "remaining_points": "điểm nữa để lên cấp tiếp theo",
        
        # Social Feed Page
        "eco_feed_title": "Bản tin Eco Social",
        "feed_sub": "Động viên sống xanh bằng cách xem các hoạt động thân thiện môi trường từ bạn bè.",
        "global_feed": "Bản tin Toàn cầu",
        "friends_feed": "Bản tin Bạn bè",
        "like": "Thích",
        "comment": "Bình luận",
        "react": "Cảm xúc Eco",
        "write_comment": "Nhập bình luận...",
        "no_actions": "Chưa có hành động Eco nào được đăng.",
        "post": "Đăng",
        
        # Friends Page
        "friends_title": "Trung tâm Bạn bè",
        "friends_sub": "Tìm kiếm bạn bè, so sánh chỉ số sống xanh và chấp nhận yêu cầu kết bạn.",
        "search_users": "Tìm người dùng",
        "send_request": "Kết bạn",
        "friend_requests": "Yêu cầu kết bạn mới",
        "pending_requests": "Yêu cầu đang chờ",
        "my_friends_list": "Danh sách Bạn bè",
        "accept": "Chấp nhận",
        "reject": "Từ chối",
        "remove": "Hủy kết bạn",
        "no_friends_found": "Chưa có người bạn nào.",
        "compare_stats": "So sánh Chỉ số",
        "your_points": "Điểm của bạn",
        "friend_points": "Điểm của bạn",
        "their_level": "Cấp của bạn",
        
        # Groups Page & Details
        "groups_title": "Nhóm Eco",
        "groups_sub": "Tham gia hoặc tạo nhóm để cùng làm Nhiệm vụ tuần và nhân đôi điểm thưởng.",
        "create_group": "Tạo nhóm mới",
        "group_name": "Tên nhóm",
        "active_quest": "Nhiệm vụ Tuần của Nhóm",
        "group_members": "Thành viên nhóm",
        "group_invites": "Lời mời vào nhóm",
        "leave_group": "Rời khỏi nhóm",
        "delete_group": "Giải tán nhóm",
        "no_groups": "Bạn chưa là thành viên của nhóm nào.",
        "invite_members": "Mời thành viên",
        "search_username": "Nhập tên tài khoản cần mời...",
        "invite_sent": "Đã gửi lời mời",
        "max_members_limit": "Chỉ giới hạn tối đa 5 thành viên.",
        "weekly_quest_desc": "Nhiệm vụ tuần nhóm",
        
        # Leaderboard Page
        "leaderboard_title": "Bảng xếp hạng Eco",
        "leaderboard_sub": "Kiểm tra xếp hạng của bạn trong cộng đồng sống xanh toàn cầu, bạn bè hoặc nhóm.",
        "global_rank": "Bảng xếp hạng Toàn cầu",
        "friends_rank": "Bảng xếp hạng Bạn bè",
        "group_rank": "Bảng xếp hạng Nhóm",
        "rank": "Hạng",
        "user": "Thành viên",
        "score": "Tổng điểm",
        
        # Frame Shop Page
        "frame_shop_title": "Cửa hàng khung ảnh đại diện",
        "frame_shop_sub": "Đổi điểm thưởng lấy các viền ảnh đại diện cao cấp có hiệu ứng động.",
        "buy": "Mua khung",
        "equip": "Sử dụng",
        "unequip": "Gỡ bỏ",
        "owned_frame": "Đã sở hữu",
        "insufficient_points": "Không đủ điểm thưởng",
        
        # Missions Center Page
        "missions_title": "Trung tâm Nhiệm vụ",
        "missions_sub": "Làm nhiệm vụ bảo vệ môi trường để nhận điểm thưởng và thăng cấp.",
        "daily_missions_list": "Nhiệm vụ hàng ngày",
        "weekly_missions_list": "Thử thách tuần",
        
        # Upload/Edit Action Page
        "upload_action_title": "Chia sẻ Hành động sống xanh",
        "upload_sub": "Chọn danh mục, tải ảnh lên và viết mô tả ngắn để được AI xác minh.",
        "edit_action_title": "Sửa hành động Eco",
        "select_image": "Chọn hình ảnh",
        "enter_caption": "Mô tả bạn đã làm gì để bảo vệ môi trường...",
        "submit_for_ai": "Gửi đi xác minh",
        "choose_file": "Chọn tệp",
        "update_action": "Cập nhật",
    }
}


def language_translations(request):
    lang = request.session.get("language", "en")
    translation_dict = TRANSLATIONS.get(lang, TRANSLATIONS["en"])
    return {
        "t": translation_dict,
        "current_lang": lang,
    }
