# Generated by Django 6.0.6 on 2026-06-24 02:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EcoAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='eco_actions/')),
                ('caption', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('recycling', 'Recycling'), ('tree_planting', 'Tree Planting'), ('green_transport', 'Green Transport'), ('clean_up', 'Clean Up'), ('saving_energy', 'Saving Energy')], max_length=50)),
                ('points', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
