# Generated by Django 6.0.4 on 2026-06-25 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_dailymission_userdailymission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=10)),
                ('requirement_category', models.CharField(choices=[('recycling', 'Recycling'), ('tree_planting', 'Tree Planting'), ('green_transport', 'Green Transport'), ('clean_up', 'Clean Up'), ('saving_energy', 'Saving Energy'), ('reusable_item', 'Reusable Item')], max_length=50)),
                ('requirement_count', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_action_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='streak_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='GroupWeeklyQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('recycling', 'Recycling'), ('tree_planting', 'Tree Planting'), ('green_transport', 'Green Transport'), ('clean_up', 'Clean Up'), ('saving_energy', 'Saving Energy'), ('reusable_item', 'Reusable Item')], max_length=50)),
                ('target_count', models.PositiveIntegerField(default=10)),
                ('start_date', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_quest', to='tracker.ecogroup')),
            ],
        ),
        migrations.CreateModel(
            name='EcoActionLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='tracker.ecoaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'action')},
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_by', to='tracker.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
