# Generated by Django 6.0.4 on 2026-06-26 01:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_badge_userprofile_last_action_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('recycling', 'Recycling'), ('tree_planting', 'Tree Planting'), ('green_transport', 'Green Transport'), ('clean_up', 'Clean Up'), ('saving_energy', 'Saving Energy'), ('reusable_item', 'Reusable Item')], max_length=50)),
                ('bonus_points', models.PositiveIntegerField(default=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='userdailymission',
            name='earned_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='UserWeeklyMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('completed_count', models.PositiveIntegerField(default=0)),
                ('required_count', models.PositiveIntegerField(default=3)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('earned_points', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_missions', to=settings.AUTH_USER_MODEL)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_missions', to='tracker.weeklymission')),
            ],
            options={
                'unique_together': {('user', 'mission', 'start_date')},
            },
        ),
    ]
