# Generated by Django 6.0.4 on 2026-06-26 12:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_weeklymission_userdailymission_earned_points_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ecoactionlike',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='ecoactionlike',
            name='reaction_type',
            field=models.CharField(default='like', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_level',
            field=models.CharField(default='Eco Novice', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_perfect_day_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='ecoactionlike',
            unique_together={('user', 'action', 'reaction_type')},
        ),
    ]
