# Generated by Django 6.0.6 on 2026-06-30 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_avatarframe_triviaquestion_userprofile_points_spent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aicoachsuggestion',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='ecoaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='groupweeklyquest',
            name='is_completed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='groupweeklyquest',
            name='start_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='userdailymission',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='userdailymission',
            name='is_completed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='usertriviasubmission',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='userweeklymission',
            name='is_completed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='userweeklymission',
            name='start_date',
            field=models.DateField(db_index=True),
        ),
    ]
