# Generated by Django 6.0.6 on 2026-06-30 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_alter_aicoachsuggestion_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecoaction',
            name='ai_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ecoaction',
            name='ai_status',
            field=models.CharField(choices=[('pending', 'Pending AI Analysis'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20),
        ),
    ]
